### ISSUE TITLE
Is it supposed to work without SSL?

### ISSUE THREAD

**Issue by luebbe** [rroemhild/hodd#3]
I have mosquitto running on a raspberry. No user, no pass, no SSL.
Cloned the repository and followed instructions. I only see a white screen with the settings button in the top right corner (tried FF and Chrome on Windows).
The settings are obviously saved, but "connect" doesn't seem to do anything.

**Comment by rroemhild** [comment]
Just tried it on my mobile phone and it works so far without SSL, but I have only access to a MQTT broker with authentication. I can setup a environment without login tomorrow.

Do you use the Websocket protocol? It's the only supported protocol.

**Comment by luebbe** [comment]
Am I missing something in the instructions? Do I need a webserver? 
I just did the three "installation" steps from readme, so I loaded index.html directly from a directory.

**Comment by rroemhild** [comment]
That's fine no webserver needed, it runs complete in your browser. Websocket is enabled on your mosquitto broker and listening on the port you entered in the settings formular? Have you seen the SSL checkbox on the right side, it's a bit inconspicuous.

**Comment by luebbe** [comment]
I unchecked SSL in the settings.
mosquitto on the raspberry is straight out of the box. I entered the default mosquitto port 1883 in the config, so maybe that was wrong?

**Comment by rroemhild** [comment]
And for anonymous auth you have to clone the repo, the release 0.3.0 has an error with empty user/pass. But you already wrote that you cloned the repo.

You can hit F12 in the browser and open the console. Maybe there is an error you can paste here.

**Comment by rroemhild** [comment]
Aaaah. You need to setup websocket. I.e. add the following to your mosquitto config file:

```
listener 8083
protocol websockets
allow_anonymous true
```

That's mosquitto code example is straight out of my head and may  not work out of the box :)

**Comment by luebbe** [comment]
yes, I cloned the repo. Everything is under windows in case that matters. When I press F5 in the browser there is one error message:

Error: WebExtension context not found! ExtensionParent.jsm:1275:13

I've got noscript on FF, but scripts are enabled. No "noscript" on chrome.

**Comment by luebbe** [comment]
So that may be worth a line in the readme :D

**Comment by rroemhild** [comment]
That's true :D

**Comment by luebbe** [comment]
Enabling websockets did the trick. I used port 9001 since that seems to be the default (googled) port.
Now I see things. Thank you 👍

**Comment by rroemhild** [comment]
Your welcome and thanks for the feedback!

**Comment by luebbe** [comment]
Hmm, after enabling websockets, I get a "connection refused" with mosquitto_sub on the raspberry on which the broker is running, I also can't connect from my windows mqtt client. If you have an idea, please drop it here. I'm tired and will call it a day now.

**Comment by rroemhild** [comment]
Try to bind the websocket protocol to the i.e. eth0. I had similar problem when I use the Raspberry Pi as a dev server, as an access point, forwarding traffic to eth0. I had to bind the websocket to eth0, so the esp's connected with the AP can connect with the MQTT protocol.

**Comment by luebbe** [comment]
Thanks. I'll RTFM of mosquitto.conf :)
