### ISSUE TITLE
Which MQTT broker has Web Sockets?

### ISSUE THREAD

**Issue by sheilbronn** [rroemhild/hodd#4]
Hi there, 
it would be good to give an example in your README for a MQTT broker that supports Web Sockets!
Thanks!

**Comment by rroemhild** [comment]
Hi,

mosquitto, emqx, vernemq to name some open source broker. I think mosquitto is a good start and I'll add it to the readme.

**Comment by sheilbronn** [comment]
Now, I tried **test.mosquitto.org** since they claim to have enabled WebSockets. However, I wasn't succesful - hodd just hung. Do you have an idea, why?

**Comment by rroemhild** [comment]
I think they use a different port for websockets, than the default in hodd. Try port 8081 with ssl enabled.

**Comment by sheilbronn** [comment]
Thanks, port **8081** on **test.mosquitto.org** works like a charm!
May I suggest putting that into the documentation plus keeping a retained example there?!
(At The moment you can see my experiments for OpenWrt/Gluon/Freifunk Monitoring there)
